### ISSUE TITLE
Instead of importing with branch use tags

### ISSUE THREAD

**Issue by harunayyildizhadi** [Thaina/google-signin-unity#10]
Could you add tags so we can have a stable code instead of whenever you pushed something on the newmigration branch we have a different build.

Instead of:
"com.google.signin": "https://github.com/Thaina/google-signin-unity.git#newmigration",

Maybe this:
"com.google.signin": "https://github.com/Thaina/google-signin-unity.git#v1.4.0.2",

**Comment by Thaina** [comment]
You mean like this? https://github.com/Thaina/google-signin-unity/tree/v0.8.3

**Comment by harunayyildizhadi** [comment]
Yes thank you
